services:
  beer-label-editor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beer_label
    networks:
      - npm_default
    restart: unless-stopped
networks:
    npm_default:
      external: true
# Pour lancer:
# docker-compose up -d --build
#
# Pour voir les logs:
# docker-compose logs -f
#
# Pour arrÃªter:
# docker-compose down
